Sync VolumeHealthMonitor variable name with other platforms
dell/csi-powerflex pull request #132
Opened 2022-09-23 09:18 UTC by khareRajshree

# Description
Change VolumeHealthMonitor variable name to healthMonitor to sync with other platforms

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/203 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Tested VolumeHealthMonitor feature by installing driver and executing 2vols helm test.

Controller pod logs:
![controller-logs](https://user-images.githubusercontent.com/69839943/191929383-da197a47-3ccc-42a9-bb2b-0f3f8557f456.PNG)

Node pod logs:
![node-logs](https://user-images.githubusercontent.com/69839943/191929431-1d9efb0c-9c17-4ca7-b73a-21e860870f68.PNG)

2022-09-23 12:40 UTC, JacobGros requested changes
Please update the comment to reflect the new variable name:
https://github.com/dell/csi-powerflex/blob/b9891bbaac95e64080cf512c48e9f807967f7b09/helm/csi-vxflexos/values.yaml#L93

2022-09-26 07:01 UTC, Deepak-Ghivari approved these changes

2022-09-26 07:14 UTC, khareRajshree commented
> Please update the comment to reflect the new variable name:
> 
> https://github.com/dell/csi-powerflex/blob/b9891bbaac95e64080cf512c48e9f807967f7b09/helm/csi-vxflexos/values.yaml#L93

Change is addressed.

2022-09-26 08:17 UTC, VamsiSiddu-7 approved these changes

2022-09-26 11:55 UTC, Deepak-Ghivari approved these changes

2022-09-26 12:28 UTC, JacobGros approved these changes
LGTM

2022-09-29 04:55 UTC, merged