CSI-Powerflex installation using centralize helm
dell/csi-powerflex pull request #234
Opened 2023-08-08 15:59 UTC by KshitijaKakde

# Description
Installation using centralize helm

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/877

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [X] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Backward compatibility is not broken

# How Has This Been Tested?

![image](https://github.com/dell/csi-powerflex/assets/111420075/d6e4bb67-4c6e-4af0-b856-f4ee290e379d)
![image](https://github.com/dell/csi-powerflex/assets/111420075/8c814af2-e090-4f94-b2a2-c3154c05afec)
![image](https://github.com/dell/csi-powerflex/assets/111420075/0e93ffea-8fd0-43d4-8b7f-d4503e569463)

2023-08-09 05:40 UTC, VamsiSiddu-7 submitted a review, later dismissed

2023-08-09 05:50 UTC, ashleyvjoy approved these changes

2023-08-18 07:29 UTC, VamsiSiddu-7 requested changes
Needs changes. refer the comments

2023-08-18 07:29 UTC, VamsiSiddu-7 commented on dell-csi-helm-installer/csi-install.sh
> +kMajorVersion=$(run_command kubectl version | grep 'Server Version' | sed -e 's/^.*Major:"//' -e 's/[^0-9].*//g')
Why are you changing this regex?

2023-08-18 07:29 UTC, VamsiSiddu-7 commented on dell-csi-helm-installer/csi-install.sh
> +  REPOREF="release-v1.8.0"
release-v1.8.0 should not be hardcoded it should be passed from a cmd line parameter. based on the parameter it should be set

2023-08-18 07:29 UTC, VamsiSiddu-7 commented on dell-csi-helm-installer/csi-install.sh
> +if git ls-remote --quiet --tag  https://github.com/dell/helm-charts | grep -q "tags/${HELMCHARTAG}"; then
why do we need this check?

2023-08-18 07:29 UTC, VamsiSiddu-7 commented on dell-csi-helm-installer/csi-offline-bundle.sh
> +  REPOREF="release-v1.8.0"
same comments here

2023-08-18 07:57 UTC, VamsiSiddu-7 commented on dell-csi-helm-installer/csi-install.sh
> +if git ls-remote --quiet --tag  https://github.com/dell/helm-charts | grep -q "tags/${HELMCHARTAG}"; then
the latest version will be always present

2023-08-21 04:59 UTC, VamsiSiddu-7 submitted a review, later dismissed
Changes looks good to me i hope you tested both offline and helm.

2023-08-21 07:56 UTC, khareRajshree approved these changes

2023-08-21 10:16 UTC, merged