Updated go mod references for dell-csi-extensions
dell/csi-powerflex pull request #241
Opened 2023-08-28 14:11 UTC by santhoshatdell

# Description
Updated go mod references for dell-csi-extensions.
Currently set as draft PR till driver team updates Go to 1.21 and test.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/885 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage (90.1%)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

2023-08-28 14:16 UTC, harshaatdell approved these changes

2023-08-28 15:55 UTC, donatwork submitted a review, later dismissed

2023-08-29 09:27 UTC, VamsiSiddu-7 approved these changes

2023-08-29 09:29 UTC, VamsiSiddu-7 requested changes
please add the tests describing how you tested this change. Thanks

2023-08-31 14:02 UTC, santhoshatdell commented
> please add the tests describing how you tested this change. Thanks

Go 1.21 change is merged as part of another PR. This PR is kept minimal with changes only for dell-csi-extensions.

2023-08-31 14:10 UTC, VamsiSiddu-7 approved these changes

2023-08-31 14:16 UTC, merged