Update offline bundle instructions from CSI to CSM Operator
dell/csi-powerflex pull request #273
Opened 2023-12-14 18:09 UTC by KerryKovacevic

# Description
Updated documentation for offline bundle installation from referencing CSI Operator to CSM Operator.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1081|

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2023-12-14 19:23 UTC, bharathsreekanth reviewed
I have reviewed powerflex but my comments will apply across all the others.

2023-12-14 19:23 UTC, bharathsreekanth commented on dell-csi-helm-installer/csi-offline-bundle.md
> +The `csi-offline-bundle.sh` script can be used to create a package usable for offline installation of the Dell EMC CSI Storage Providers, via Helm.
minor edit, change to : 
The `csi-offline-bundle.sh` script can be used to create a package for offline installation of Dell CSI storage providers for deployment via HELM.

2023-12-14 19:23 UTC, bharathsreekanth commented on dell-csi-helm-installer/csi-offline-bundle.md
> +1. Perform a `git clone` of the desired repository. For a helm based install, the specific driver repo should be cloned. For an Operator based deployment, the Dell CSM Operator repo should be cloned
Change helm to HELM or Helm (use this same convention everywhere). Sorry, I know some of these are legacy and not really in the scope of this PR, but I think a search and replace might be easy to drive consistency.

2023-12-14 21:47 UTC, KerryKovacevic commented
> I have reviewed powerflex but my comments will apply across all the others.

Updated, will fix for the rest of the repos as well.

2023-12-15 04:12 UTC, shanmydell requested changes
![image](https://github.com/dell/csi-powerflex/assets/82038610/bc440729-489a-47aa-a0b3-7fd026724026)
Needs to be updated

2023-12-18 15:40 UTC, bharathsreekanth submitted a review, later dismissed
TY @KerryKovacevic for these changes

2023-12-19 14:51 UTC, PeresKereotubo submitted a review, later dismissed

2023-12-20 12:07 UTC, adarsh-dell approved these changes

2023-12-20 12:35 UTC, bharathsreekanth approved these changes

2023-12-20 13:00 UTC, shanmydell approved these changes

2023-12-20 13:00 UTC, merged