Nas name issue fix
dell/csi-powerflex pull request #283
Opened 2024-02-05 09:29 UTC by adarsh-dell

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-02-05 11:14 UTC, shanmydell submitted a review, later dismissed

2024-02-06 05:11 UTC, suryagupta4 submitted a review, later dismissed

2024-02-06 05:54 UTC, AkshaySainiDell requested changes

2024-02-06 05:54 UTC, AkshaySainiDell commented on service/controller.go
> +			nasName = (arr.NasName) // Secrets next
```suggestion
			nasName = arr.NasName // Secret next
```

2024-02-06 05:54 UTC, AkshaySainiDell commented on service/service.go
> +		// even though NasName is not present but PowerFlex version is >=4.0 we support NFS.
```suggestion
		// Even though NasName is not present in secret but PowerFlex version is >=4.0; we support NFS.
```

2024-02-06 05:54 UTC, AkshaySainiDell commented on service/service.go
>  			str := ""
```suggestion
```

2024-02-06 05:54 UTC, AkshaySainiDell commented on test/integration/step_defs_test.go
>  			str := ""
```suggestion
```

2024-02-06 05:54 UTC, AkshaySainiDell commented on test/integration/step_defs_test.go
> +				c.NasName = str
```suggestion
				c.NasName = ""
```

2024-02-06 05:54 UTC, AkshaySainiDell commented on service/service.go
> +				c.NasName = str
```suggestion
				c.NasName = ""
```

2024-02-06 07:00 UTC, KshitijaKakde approved these changes

2024-02-06 07:27 UTC, AkshaySainiDell approved these changes

2024-02-06 07:28 UTC, KshitijaKakde approved these changes

2024-02-06 07:28 UTC, merged