support 1.24 k8s
dell/csi-powerflex pull request #91
Opened 2022-05-16 20:40 UTC by yifeijin

# Description
This PR adds supports for k8s 1.24 driver installation.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2022-05-17 11:46 UTC, bharathsreekanth submitted a review, later dismissed

2022-05-17 11:46 UTC, bharathsreekanth commented on dell-csi-helm-installer/verify-csi-vxflexos.sh
> +  verify_k8s_versions "1.20" "1.24"
should 1.20 be changed to reflect new min version supported?

2022-05-17 21:06 UTC, JacobGros approved these changes
I agree with Bharath- we should bump up min. version

2022-05-19 19:25 UTC, JacobGros approved these changes

2022-05-19 19:26 UTC, bharathsreekanth approved these changes

2022-05-19 19:27 UTC, bharathsreekanth requested changes

2022-05-19 19:27 UTC, bharathsreekanth commented on helm/csi-vxflexos/Chart.yaml
> +# kubeVersion: ">= 1.21.0-0 < 1.25.0-0"
If we make it < 1.25, would that imply 1.24.X is supported as well? Should we just keep it <= 1.24?

2022-05-19 19:32 UTC, bharathsreekanth approved these changes

2022-05-19 19:33 UTC, merged